### PR TITLE
Use correct separator in keywords.txt

### PR DESCRIPTION
**Pull request by per1234**
The Arduino IDE currently requires the use of a single true tab separator between the name and identifier. Without this tab the keyword is not highlighted.

Reference:
https://github.com/arduino/Arduino/wiki/Arduino-IDE-1.5:-Library-specification#keywords

### CODE REVIEW

**Comment by per1234** [comment]
You're welcome?

**Comment by jorgemvc** [comment]
Hello, I just fixed the issue.

**Comment by jorgemvc** [comment]
Hello @per1234, I am new with this. I fixed the issues you found and closed them, what I have to do now ?

**Comment by per1234** [comment]
Typically when someone submits a pull request you only need to review the proposal to make sure it is acceptable and then click the "Merge" button to have GitHub automatically make the proposed change to your code (see https://help.github.com/articles/merging-a-pull-request/). If you prefer to make the change manually that's fine with me (if inefficient) but it would be courteous to make a short comment when you close the pull request explaining why it was closed rather than merged.

When someone closes one of my pull requests without merging and doesn't give an explanation I must take some time to figure out:
- Was the pull request accidentally closed?
- Was my work so terrible that it didn't even merit an explanation of why it was rejected?

**Comment by jorgemvc** [comment]
As I told you, I am a newbie in this environment and I did not intend to bother you or been rude, I just wanted to fix the errors promptly. I am so sorry about this misunderstanding.

Can you please tell me what is the next step to follow ?

**Comment by per1234** [comment]
No worries. No additional steps are required. The problem has been fixed and you explained the reason for closing the pull request instead of merging it so everything is done.

**Pull request closed without merging**
